id: P003050
initial_creation_type: ocr
source_metadata:
  id: bdr:W12842
  title: གཞི་གསུམ་གྱི་ཆོ་ག་སོགས་སོ་ཐར་བླང་དོར་མདོར་བསྡུས།
  author: ''
  volumes:
    61b6fe1a4367459b9bf2bcd144afafe4:
      image_group_id: I1KG8863
      title: ''
      volume_number: 1
      total_pages: 92
