id: IEBE94498
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:46:27+00:00'
last_modified: '2022-06-07T17:13:11.833583+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W12842
  title: གཞི་གསུམ་གྱི་ཆོ་ག་སོགས་སོ་ཐར་བླང་དོར་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E6A7:
      image_group_id: I1KG8863
      title: ''
      total_pages: 92
      order: 1
      base_file: E6A7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
